import type { Article } from '@/types/news';

export const demoCiberseguridadArticles: Article[] = [
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Carlos Mendez',
    title: 'Ataque de ransomware masivo paraliza hospitales en tres países europeos',
    description: 'Un sofisticado ataque de ransomware afecta sistemas críticos de salud en Alemania, Francia e Italia, exigiendo rescate en criptomonedas.',
    url: 'https://example.com/cyber/1',
    urlToImage: 'https://readdy.ai/api/search-image?query=Hospital%20emergency%20room%20with%20digital%20screens%20showing%20ransomware%20alert%20and%20locked%20systems%2C%20dark%20cybersecurity%20atmosphere%2C%20dramatic%20blue%20and%20red%20lighting%2C%20documentary%20style&width=800&height=450&seq=cyber-01&orientation=landscape',
    publishedAt: '2026-07-14T10:00:00Z',
    content: 'Un ataque coordinado de ransomware ha paralizado sistemas informáticos en al menos 15 hospitales de tres países europeos.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'Sofia Herrera',
    title: 'Vulnerabilidad crítica en sistemas bancarios expone datos de 50 millones de usuarios',
    description: 'Investigadores descubren una falla de seguridad en software ampliamente utilizado por bancos globales que permitía acceso no autorizado a información financiera.',
    url: 'https://example.com/cyber/2',
    urlToImage: 'https://readdy.ai/api/search-image?query=Banking%20data%20center%20security%20breach%20visualization%20with%20code%20and%20data%20streams%2C%20dark%20server%20room%20with%20red%20alert%20indicators%2C%20cybersecurity%20photography%2C%20dramatic%20lighting&width=800&height=450&seq=cyber-02&orientation=landscape',
    publishedAt: '2026-07-14T07:30:00Z',
    content: 'Una vulnerabilidad de día cero en infraestructura bancaria crítica ha sido descubierta por investigadores de seguridad.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'James Mitchell',
    title: 'Ciberataque a infraestructura eléctrica deja sin luz a tres millones de personas',
    description: 'Autoridades confirman que el apagón masivo en el noreste de Estados Unidos fue provocado por un ataque dirigido a sistemas SCADA de la red eléctrica.',
    url: 'https://example.com/cyber/3',
    urlToImage: 'https://readdy.ai/api/search-image?query=Dark%20city%20skyline%20during%20massive%20blackout%20with%20only%20emergency%20lights%20visible%2C%20critical%20infrastructure%20failure%2C%20dramatic%20night%20photography%2C%20ominous%20atmosphere&width=800&height=450&seq=cyber-03&orientation=landscape',
    publishedAt: '2026-07-13T16:00:00Z',
    content: 'Un ciberataque sin precedentes contra la infraestructura eléctrica estadounidense ha dejado a millones sin electricidad.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Ana Torres',
    title: 'Microsoft lanza parche de emergencia para vulnerabilidad zero-day en Windows',
    description: 'La actualización crítica corrige una falla explotada activamente por grupos de ciberespionaje para instalar malware en sistemas corporativos.',
    url: 'https://example.com/cyber/4',
    urlToImage: 'https://readdy.ai/api/search-image?query=Windows%20security%20update%20interface%20with%20patch%20installation%20progress%2C%20modern%20desktop%20setup%2C%20cybersecurity%20software%20photography%2C%20blue%20tech%20aesthetic&width=800&height=450&seq=cyber-04&orientation=landscape',
    publishedAt: '2026-07-13T12:00:00Z',
    content: 'Microsoft ha lanzado una actualización de seguridad fuera de ciclo para corregir una vulnerabilidad crítica en Windows.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Maria Gonzalez',
    title: 'OTAN activa protocolo de ciberdefensa colectiva tras ataque a país miembro',
    description: 'Por primera vez en la historia, la alianza invoca el Artículo 5 digital en respuesta a un ciberataque patrocinado por un estado contra infraestructura gubernamental.',
    url: 'https://example.com/cyber/5',
    urlToImage: 'https://readdy.ai/api/search-image?query=NATO%20headquarters%20cybersecurity%20command%20center%20with%20world%20map%20showing%20cyber%20threats%2C%20military%20digital%20operations%20room%2C%20formal%20institutional%20photography%2C%20blue%20glow&width=800&height=450&seq=cyber-05&orientation=landscape',
    publishedAt: '2026-07-13T09:00:00Z',
    content: 'La OTAN ha tomado una decisión histórica al activar por primera vez su cláusula de defensa colectiva para ciberataques.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Pedro Alvarez',
    title: 'Startup de ciberseguridad detecta amenazas con IA predictiva y recauda $300 millones',
    description: 'La plataforma utiliza modelos de machine learning para anticipar ataques antes de que ocurran, analizando patrones de comportamiento en tiempo real.',
    url: 'https://example.com/cyber/6',
    urlToImage: 'https://readdy.ai/api/search-image?query=AI%20cybersecurity%20dashboard%20showing%20predictive%20threat%20analysis%20and%20network%20visualization%2C%20modern%20security%20operations%20center%2C%20tech%20startup%20photography%2C%20sleek%20interface%20design&width=800&height=450&seq=cyber-06&orientation=landscape',
    publishedAt: '2026-07-12T15:00:00Z',
    content: 'Una startup de ciberseguridad ha desarrollado un sistema de IA que promete revolucionar la detección de amenazas.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: null,
    title: 'Google revela que ciberataques patrocinados por estados aumentaron 200% en 2026',
    description: 'El informe anual de Threat Analysis Group muestra una escalada sin precedentes en operaciones de ciberespionaje y desinformación.',
    url: 'https://example.com/cyber/7',
    urlToImage: 'https://readdy.ai/api/search-image?query=Google%20cybersecurity%20threat%20analysis%20report%20with%20global%20attack%20map%20and%20statistics%2C%20corporate%20security%20presentation%2C%20professional%20tech%20photography%2C%20data%20visualization&width=800&height=450&seq=cyber-07&orientation=landscape',
    publishedAt: '2026-07-12T11:00:00Z',
    content: 'El equipo de análisis de amenazas de Google ha publicado su informe anual con cifras alarmantes.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Elena Vargas',
    title: 'Deepfakes de audio burlan sistemas de autenticación bancaria por teléfono',
    description: 'Criminales utilizan voces sintetizadas con IA para suplantar identidades y realizar transferencias fraudulentas millonarias.',
    url: 'https://example.com/cyber/8',
    urlToImage: 'https://readdy.ai/api/search-image?query=Voice%20authentication%20security%20system%20being%20bypassed%20by%20AI%20deepfake%20technology%2C%20abstract%20waveform%20visualization%20with%20red%20warning%20signals%2C%20dark%20cybersecurity%20aesthetic&width=800&height=450&seq=cyber-08&orientation=landscape',
    publishedAt: '2026-07-11T16:00:00Z',
    content: 'Los sistemas de verificación de identidad por voz están siendo comprometidos por una nueva generación de deepfakes de audio.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'Laura Castillo',
    title: 'Escuelas primarias, nuevo blanco de ciberdelincuentes: ransomware en la educación',
    description: 'Más de 500 distritos escolares reportan ataques este año, con datos de estudiantes y personal comprometidos en filtraciones masivas.',
    url: 'https://example.com/cyber/9',
    urlToImage: 'https://readdy.ai/api/search-image?query=Elementary%20school%20classroom%20with%20computer%20screens%20showing%20ransomware%20lock%20message%2C%20educational%20technology%20environment%2C%20documentary%20photography%2C%20concerned%20atmosphere&width=800&height=450&seq=cyber-09&orientation=landscape',
    publishedAt: '2026-07-11T10:00:00Z',
    content: 'El sector educativo se ha convertido en uno de los objetivos preferidos de los grupos de ransomware.',
  },
  {
    source: { id: 'ars-technica', name: 'Ars Technica' },
    author: 'Diego Ramirez',
    title: 'Nuevo estándar de cifrado post-cuántico aprobado por el NIST entra en vigor',
    description: 'El estándar CRYSTALS-Kyber se implementa globalmente para proteger sistemas contra la amenaza futura de computadoras cuánticas capaces de romper el cifrado actual.',
    url: 'https://example.com/cyber/10',
    urlToImage: 'https://readdy.ai/api/search-image?query=Post-quantum%20cryptography%20visualization%20with%20complex%20mathematical%20lattice%20structures%20and%20encryption%20keys%2C%20digital%20security%20concept%2C%20futuristic%20tech%20photography%2C%20clean%20geometric%20patterns&width=800&height=450&seq=cyber-10&orientation=landscape',
    publishedAt: '2026-07-11T08:00:00Z',
    content: 'El nuevo estándar de cifrado resistente a computadoras cuánticas ha comenzado su implementación global.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Michael Torres',
    title: 'Ciberataque interrumpe cadena de suministro global de semiconductores',
    description: 'Un ataque dirigido contra un importante fabricante de chips en Taiwán provoca escasez y retrasos en la industria tecnológica mundial.',
    url: 'https://example.com/cyber/11',
    urlToImage: 'https://readdy.ai/api/search-image?query=Semiconductor%20manufacturing%20facility%20with%20production%20line%20halted%20and%20security%20breach%20indicators%2C%20clean%20room%20environment%2C%20industrial%20cybersecurity%20photography%2C%20sterile%20blue%20lighting&width=800&height=450&seq=cyber-11&orientation=landscape',
    publishedAt: '2026-07-10T17:00:00Z',
    content: 'La industria global de semiconductores enfrenta una nueva crisis tras un ciberataque a uno de sus principales fabricantes.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Sofia Herrera',
    title: 'WhatsApp implementa cifrado de extremo a extremo con verificación biométrica',
    description: 'La nueva capa de seguridad requiere autenticación facial para acceder a conversaciones cifradas, elevando el estándar de privacidad en mensajería.',
    url: 'https://example.com/cyber/12',
    urlToImage: 'https://readdy.ai/api/search-image?query=Smartphone%20messaging%20app%20with%20biometric%20facial%20recognition%20security%20overlay%2C%20modern%20mobile%20UX%20design%2C%20digital%20privacy%20photography%2C%20clean%20interface%20aesthetic&width=800&height=450&seq=cyber-12&orientation=landscape',
    publishedAt: '2026-07-10T13:00:00Z',
    content: 'WhatsApp ha anunciado la mayor actualización de seguridad en la historia de la plataforma de mensajería.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Ana Torres',
    title: 'Ciberespionaje gubernamental utiliza dispositivos IoT domésticos como puerta de entrada',
    description: 'Investigadores revelan campaña de espionaje que compromete cámaras de seguridad, termostatos y altavoces inteligentes para infiltrar redes corporativas desde casa.',
    url: 'https://example.com/cyber/13',
    urlToImage: 'https://readdy.ai/api/search-image?query=Smart%20home%20IoT%20devices%20compromised%20with%20spyware%20indicators%2C%20modern%20living%20room%20with%20hidden%20cyber%20threats%20visualization%2C%20domestic%20surveillance%20photography%2C%20unsettling%20atmosphere&width=800&height=450&seq=cyber-13&orientation=landscape',
    publishedAt: '2026-07-09T14:00:00Z',
    content: 'Los dispositivos inteligentes del hogar se han convertido en el vector de ataque más novedoso para el ciberespionaje.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'James Mitchell',
    title: 'Filtración masiva en LinkedIn expone datos de 700 millones de profesionales',
    description: 'Una base de datos con información detallada de perfiles profesionales aparece a la venta en foros de la dark web por 50 bitcoins.',
    url: 'https://example.com/cyber/14',
    urlToImage: 'https://readdy.ai/api/search-image?query=Data%20breach%20visualization%20with%20LinkedIn%20professional%20data%20leaking%20into%20dark%20web%20marketplace%2C%20digital%20security%20crisis%2C%20dark%20background%20with%20red%20data%20streams%2C%20cybersecurity%20photography&width=800&height=450&seq=cyber-14&orientation=landscape',
    publishedAt: '2026-07-09T10:00:00Z',
    content: 'Una de las mayores filtraciones de datos de la historia afecta a la plataforma profesional LinkedIn.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Carlos Mendez',
    title: 'El Pentágono crea unidad de ciberguerra ofensiva con capacidades autónomas',
    description: 'La nueva división militar integra sistemas de IA para ejecutar operaciones cibernéticas ofensivas con mínima intervención humana.',
    url: 'https://example.com/cyber/15',
    urlToImage: 'https://readdy.ai/api/search-image?query=Pentagon%20cyber%20warfare%20command%20center%20with%20military%20personnel%20monitoring%20global%20network%20operations%2C%20classified%20military%20facility%2C%20strategic%20defense%20photography%2C%20dark%20tactical%20environment&width=800&height=450&seq=cyber-15&orientation=landscape',
    publishedAt: '2026-07-08T18:00:00Z',
    content: 'El Departamento de Defensa de Estados Unidos ha anunciado la creación de una nueva unidad de ciberoperaciones ofensivas.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: null,
    title: 'Interpol desmantela red global de ciberestafas que operaba en 40 países',
    description: 'La operación coordinada resultó en más de 200 arrestos y la confiscación de $150 millones en activos digitales de organizaciones criminales.',
    url: 'https://example.com/cyber/16',
    urlToImage: 'https://readdy.ai/api/search-image?query=Interpol%20cybercrime%20operation%20with%20international%20law%20enforcement%20coordination%20center%2C%20world%20map%20with%20arrest%20locations%2C%20formal%20police%20photography%2C%20tactical%20command%20room&width=800&height=450&seq=cyber-16&orientation=landscape',
    publishedAt: '2026-07-08T14:00:00Z',
    content: 'Una operación internacional sin precedentes ha logrado desmantelar una de las redes de cibercrimen más grandes del mundo.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Pedro Alvarez',
    title: 'Apple cierra falla que permitía acceso remoto a iPhones sin interacción del usuario',
    description: 'La vulnerabilidad, calificada como crítica, afectaba a todos los modelos desde iPhone 12 y fue explotada por software espía comercial.',
    url: 'https://example.com/cyber/17',
    urlToImage: 'https://readdy.ai/api/search-image?query=iPhone%20security%20vulnerability%20patch%20notification%20on%20device%20screen%2C%20close-up%20smartphone%20photography%2C%20Apple%20ecosystem%20security%2C%20clean%20product%20photography%20with%20warning%20elements&width=800&height=450&seq=cyber-17&orientation=landscape',
    publishedAt: '2026-07-07T15:00:00Z',
    content: 'Apple ha lanzado una actualización de emergencia para corregir una vulnerabilidad que afectaba a millones de iPhones.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Elena Vargas',
    title: 'Ciberataque a bolsa de valores detiene operaciones durante cuatro horas',
    description: 'El ataque DDoS más grande registrado contra infraestructura financiera interrumpe temporalmente el comercio electrónico en mercados asiáticos.',
    url: 'https://example.com/cyber/18',
    urlToImage: 'https://readdy.ai/api/search-image?query=Stock%20exchange%20trading%20floor%20with%20frozen%20digital%20displays%20showing%20DDoS%20attack%20alert%2C%20financial%20district%20crisis%2C%20dramatic%20business%20photography%2C%20red%20emergency%20lighting&width=800&height=450&seq=cyber-18&orientation=landscape',
    publishedAt: '2026-07-07T10:30:00Z',
    content: 'Los mercados financieros asiáticos sufrieron una interrupción significativa debido a un ciberataque masivo.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Diego Ramirez',
    title: 'Autenticación sin contraseña se convierte en estándar obligatorio de la industria',
    description: 'La alianza FIDO anuncia que las principales plataformas tecnológicas eliminarán las contraseñas tradicionales para 2027, adoptando passkeys biométricas.',
    url: 'https://example.com/cyber/19',
    urlToImage: 'https://readdy.ai/api/search-image?query=Passwordless%20authentication%20future%20concept%20with%20biometric%20passkey%20symbols%20and%20digital%20identity%2C%20modern%20security%20UX%20design%2C%20tech%20innovation%20photography%2C%20clean%20white%20and%20gold%20aesthetic&width=800&height=450&seq=cyber-19&orientation=landscape',
    publishedAt: '2026-07-06T16:00:00Z',
    content: 'La industria tecnológica ha alcanzado un acuerdo histórico para eliminar las contraseñas tradicionales.',
  },
  {
    source: { id: 'ars-technica', name: 'Ars Technica' },
    author: 'Laura Castillo',
    title: 'Investigadores crean firewall cuántico que detecta ataques en tiempo real',
    description: 'El sistema utiliza principios de entrelazamiento cuántico para identificar intrusiones a nivel de paquete de red con precisión sin precedentes.',
    url: 'https://example.com/cyber/20',
    urlToImage: 'https://readdy.ai/api/search-image?query=Quantum%20firewall%20technology%20visualization%20with%20entangled%20particles%20detecting%20network%20intrusions%2C%20futuristic%20cybersecurity%20lab%2C%20scientific%20computing%20photography%2C%20quantum%20blue%20glow&width=800&height=450&seq=cyber-20&orientation=landscape',
    publishedAt: '2026-07-06T12:00:00Z',
    content: 'La computación cuántica está encontrando aplicaciones revolucionarias en el campo de la ciberseguridad.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'Maria Gonzalez',
    title: 'Gobiernos invierten $20 mil millones en ciberseguridad para infraestructura crítica',
    description: 'El gasto global en protección de redes eléctricas, agua y transporte se duplica en respuesta a la creciente amenaza de ciberataques patrocinados por estados.',
    url: 'https://example.com/cyber/21',
    urlToImage: 'https://readdy.ai/api/search-image?query=Government%20cybersecurity%20operations%20center%20protecting%20critical%20infrastructure%20with%20world%20map%20and%20threat%20indicators%2C%20national%20security%20facility%2C%20official%20photography%2C%20strategic%20command&width=800&height=450&seq=cyber-21&orientation=landscape',
    publishedAt: '2026-07-06T09:00:00Z',
    content: 'La inversión global en ciberseguridad para infraestructura crítica ha alcanzado niveles récord.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Ana Torres',
    title: 'Ciberdelincuentes usan IA generativa para crear campañas de phishing indetectables',
    description: 'Los nuevos ataques de ingeniería social generados por IA logran tasas de éxito del 60%, muy por encima del 5% de los métodos tradicionales.',
    url: 'https://example.com/cyber/22',
    urlToImage: 'https://readdy.ai/api/search-image?query=AI-generated%20phishing%20email%20being%20analyzed%20by%20cybersecurity%20software%2C%20split%20screen%20showing%20attack%20and%20defense%2C%20digital%20threat%20analysis%20photography%2C%20dramatic%20red%20vs%20blue%20lighting&width=800&height=450&seq=cyber-22&orientation=landscape',
    publishedAt: '2026-07-05T14:00:00Z',
    content: 'La inteligencia artificial generativa está siendo utilizada por ciberdelincuentes para crear ataques de phishing extremadamente sofisticados.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'Michael Torres',
    title: 'Unión Europea multa con 1.200 millones de euros a plataforma por violación de datos',
    description: 'La sanción récord bajo el GDPR se impone por transferencia inadecuada de datos de ciudadanos europeos y fallos en las medidas de seguridad.',
    url: 'https://example.com/cyber/23',
    urlToImage: 'https://readdy.ai/api/search-image?query=European%20Union%20GDPR%20fine%20announcement%20with%20legal%20documents%20and%20digital%20privacy%20scales%2C%20Brussels%20institutional%20photography%2C%20formal%20government%20setting%2C%20official%20atmosphere&width=800&height=450&seq=cyber-23&orientation=landscape',
    publishedAt: '2026-07-04T18:00:00Z',
    content: 'La Unión Europea ha impuesto la multa más alta de su historia por violaciones de protección de datos.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Carlos Mendez',
    title: 'Ciberseguridad en la nube: el 80% de las empresas migrarán a arquitectura zero-trust',
    description: 'El modelo de seguridad que no confía en nadie por defecto se convierte en el estándar corporativo ante el aumento de brechas en entornos cloud.',
    url: 'https://example.com/cyber/24',
    urlToImage: 'https://readdy.ai/api/search-image?query=Zero-trust%20network%20security%20architecture%20diagram%20with%20corporate%20cloud%20infrastructure%2C%20modern%20enterprise%20cybersecurity%2C%20professional%20tech%20photography%2C%20blue%20and%20white%20minimalist&width=800&height=450&seq=cyber-24&orientation=landscape',
    publishedAt: '2026-07-04T10:00:00Z',
    content: 'El modelo de seguridad zero-trust está experimentando una adopción masiva en el entorno empresarial.',
  },
];