import type { Article } from '@/types/news';

export const demoInteligenciaArtificialArticles: Article[] = [
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Ana Torres',
    title: 'OpenAI presenta nuevo modelo con capacidades de razonamiento avanzado',
    description: 'El nuevo modelo supera benchmarks anteriores en matemáticas, programación y razonamiento lógico, marcando un hito en IA generativa.',
    url: 'https://example.com/ai/1',
    urlToImage: 'https://readdy.ai/api/search-image?query=Futuristic%20AI%20research%20laboratory%20with%20holographic%20neural%20network%20visualizations%2C%20clean%20white%20environment%20with%20subtle%20blue%20light%2C%20professional%20tech%20photography%2C%20minimalist%20aesthetic&width=800&height=450&seq=trends-ai-01&orientation=landscape',
    publishedAt: '2026-07-14T09:00:00Z',
    content: 'OpenAI ha presentado su modelo más avanzado hasta la fecha, con capacidades de razonamiento que superan significativamente a versiones anteriores.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Pedro Alvarez',
    title: 'Startup de IA recauda $2 mil millones para desarrollar chips especializados',
    description: 'La inversión récord impulsa el desarrollo de hardware diseñado exclusivamente para modelos de inteligencia artificial de próxima generación.',
    url: 'https://example.com/ai/2',
    urlToImage: 'https://readdy.ai/api/search-image?query=Advanced%20semiconductor%20chip%20manufacturing%20facility%20with%20precision%20robotic%20arms%20and%20clean%20room%20environment%2C%20blue%20and%20white%20tones%2C%20high-tech%20industrial%20photography&width=800&height=450&seq=trends-ai-02&orientation=landscape',
    publishedAt: '2026-07-14T08:00:00Z',
    content: 'Una startup de Silicon Valley ha asegurado la mayor ronda de financiación en la historia del hardware para inteligencia artificial.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Carlos Mendez',
    title: 'La Unión Europea aprueba el reglamento definitivo de inteligencia artificial',
    description: 'Tras años de debate, la UE implementa el marco regulatorio más completo del mundo para sistemas de IA, clasificando aplicaciones por nivel de riesgo.',
    url: 'https://example.com/ai/3',
    urlToImage: 'https://readdy.ai/api/search-image?query=European%20Parliament%20chamber%20with%20digital%20AI%20regulation%20documents%20displayed%20on%20large%20screens%2C%20formal%20government%20setting%2C%20professional%20photojournalism%20style&width=800&height=450&seq=trends-ai-03&orientation=landscape',
    publishedAt: '2026-07-13T14:30:00Z',
    content: 'El Parlamento Europeo ha dado luz verde final al Reglamento de Inteligencia Artificial, creando el marco legal más ambicioso del mundo para esta tecnología.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'James Mitchell',
    title: 'Inteligencia artificial detecta cáncer de mama con 98% de precisión en estudio clínico',
    description: 'Un sistema de IA desarrollado por investigadores del MIT supera a radiólogos humanos en la detección temprana de tumores malignos.',
    url: 'https://example.com/ai/4',
    urlToImage: 'https://readdy.ai/api/search-image?query=Medical%20professional%20reviewing%20AI-assisted%20breast%20cancer%20screening%20results%20on%20digital%20display%2C%20modern%20hospital%20setting%2C%20clean%20clinical%20photography%2C%20warm%20professional%20lighting&width=800&height=450&seq=trends-ai-04&orientation=landscape',
    publishedAt: '2026-07-13T10:00:00Z',
    content: 'Un innovador sistema de inteligencia artificial ha demostrado una precisión sin precedentes en la detección de cáncer de mama.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'Sofia Herrera',
    title: 'Gigantes tecnológicos compiten por talento de IA con salarios millonarios',
    description: 'Google, Microsoft y Meta intensifican la guerra por investigadores de inteligencia artificial, ofreciendo paquetes de compensación sin precedentes.',
    url: 'https://example.com/ai/5',
    urlToImage: 'https://readdy.ai/api/search-image?query=Modern%20tech%20campus%20headquarters%20with%20diverse%20professionals%20collaborating%20in%20open%20workspace%2C%20glass%20architecture%2C%20natural%20light%2C%20corporate%20lifestyle%20photography&width=800&height=450&seq=trends-ai-05&orientation=landscape',
    publishedAt: '2026-07-13T07:00:00Z',
    content: 'La competencia por el talento en inteligencia artificial ha alcanzado niveles sin precedentes en Silicon Valley.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Elena Vargas',
    title: 'Nvidia revela arquitectura de GPU que duplica el rendimiento en entrenamiento de IA',
    description: 'La nueva generación de chips promete reducir a la mitad el tiempo necesario para entrenar modelos de lenguaje de gran escala.',
    url: 'https://example.com/ai/6',
    urlToImage: 'https://readdy.ai/api/search-image?query=Nvidia%20GPU%20chip%20architecture%20close-up%20with%20intricate%20circuit%20patterns%20and%20green%20LED%20glow%2C%20dark%20tech%20background%2C%20hardware%20product%20photography%2C%20premium%20aesthetic&width=800&height=450&seq=trends-ai-06&orientation=landscape',
    publishedAt: '2026-07-12T16:00:00Z',
    content: 'Nvidia ha presentado su nueva arquitectura de GPU diseñada específicamente para cargas de trabajo de inteligencia artificial.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Maria Gonzalez',
    title: 'IA generativa transforma la industria del cine: polémica y oportunidades',
    description: 'Estudios de Hollywood comienzan a integrar herramientas de IA en producción, mientras sindicatos exigen regulaciones para proteger empleos creativos.',
    url: 'https://example.com/ai/7',
    urlToImage: 'https://readdy.ai/api/search-image?query=Film%20production%20set%20with%20digital%20screens%20showing%20AI-generated%20visual%20effects%2C%20professional%20movie%20studio%20environment%2C%20cinematic%20lighting%2C%20entertainment%20industry%20photography&width=800&height=450&seq=trends-ai-07&orientation=landscape',
    publishedAt: '2026-07-12T11:30:00Z',
    content: 'La industria cinematográfica se encuentra en una encrucijada ante el avance imparable de la inteligencia artificial generativa.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Diego Ramirez',
    title: 'Asistentes de IA con memoria a largo plazo llegan a dispositivos móviles',
    description: 'Nuevos smartphones integran chips neuronales capaces de ejecutar modelos de lenguaje localmente sin conexión a internet.',
    url: 'https://example.com/ai/8',
    urlToImage: 'https://readdy.ai/api/search-image?query=Smartphone%20displaying%20futuristic%20AI%20assistant%20interface%20with%20holographic%20elements%2C%20modern%20minimal%20setting%2C%20product%20photography%20with%20soft%20lighting%2C%20clean%20aesthetic&width=800&height=450&seq=trends-ai-08&orientation=landscape',
    publishedAt: '2026-07-11T14:00:00Z',
    content: 'La próxima generación de teléfonos inteligentes incorporará capacidades de IA que antes solo estaban disponibles en la nube.',
  },
  {
    source: { id: 'ars-technica', name: 'Ars Technica' },
    author: null,
    title: 'Modelos de lenguaje open source alcanzan paridad con soluciones propietarias',
    description: 'La comunidad de código abierto demuestra que los modelos públicos igualan el rendimiento de GPT y Gemini en múltiples benchmarks.',
    url: 'https://example.com/ai/9',
    urlToImage: 'https://readdy.ai/api/search-image?query=Open%20source%20code%20repository%20visualization%20with%20network%20graph%20and%20collaboration%20data%2C%20dark%20terminal%20aesthetic%20with%20green%20matrix-style%20elements%2C%20tech%20culture%20photography&width=800&height=450&seq=trends-ai-09&orientation=landscape',
    publishedAt: '2026-07-11T09:00:00Z',
    content: 'Un hito importante para la inteligencia artificial de código abierto se ha alcanzado esta semana.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'Laura Castillo',
    title: 'Escuelas británicas integran tutores de IA en el aula con resultados prometedores',
    description: 'Un programa piloto en 500 escuelas muestra mejoras significativas en matemáticas y comprensión lectora con apoyo de IA personalizada.',
    url: 'https://example.com/ai/10',
    urlToImage: 'https://readdy.ai/api/search-image?query=Diverse%20classroom%20with%20students%20using%20tablets%20and%20interactive%20AI%20learning%20tools%2C%20modern%20educational%20environment%2C%20natural%20daylight%2C%20warm%20documentary%20photography%20style&width=800&height=450&seq=trends-ai-10&orientation=landscape',
    publishedAt: '2026-07-11T06:30:00Z',
    content: 'El sistema educativo británico está experimentando una transformación silenciosa con la introducción de tutores basados en inteligencia artificial.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'Michael Torres',
    title: 'Foro Económico Mundial: IA podría automatizar el 40% de trabajos actuales para 2035',
    description: 'Un informe presentado en Davos advierte sobre la necesidad urgente de programas de recapacitación masiva a nivel global.',
    url: 'https://example.com/ai/11',
    urlToImage: 'https://readdy.ai/api/search-image?query=World%20Economic%20Forum%20conference%20hall%20with%20global%20leaders%20and%20digital%20economic%20data%20visualization%20screens%2C%20formal%20summit%20atmosphere%2C%20professional%20event%20photography&width=800&height=450&seq=trends-ai-11&orientation=landscape',
    publishedAt: '2026-07-10T18:00:00Z',
    content: 'El Foro Económico Mundial ha publicado un informe que sacude los cimientos del mercado laboral global.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Carlos Mendez',
    title: 'DeepMind logra avance histórico en plegamiento de proteínas con IA',
    description: 'AlphaFold 4 puede predecir interacciones entre proteínas y fármacos, acelerando el desarrollo de nuevos medicamentos.',
    url: 'https://example.com/ai/12',
    urlToImage: 'https://readdy.ai/api/search-image?query=Scientific%20visualization%20of%20protein%20folding%20with%20colorful%20molecular%20structures%20in%203D%2C%20research%20laboratory%20setting%2C%20cutting-edge%20science%20photography%2C%20blue%20and%20white%20tones&width=800&height=450&seq=trends-ai-12&orientation=landscape',
    publishedAt: '2026-07-10T14:00:00Z',
    content: 'DeepMind ha alcanzado un nuevo hito científico con la última versión de AlphaFold.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Ana Torres',
    title: 'El debate ético: ¿deberían los sistemas de IA tener personalidad jurídica?',
    description: 'Expertos en derecho y tecnología discuten si los sistemas autónomos avanzados requieren un nuevo marco de responsabilidad legal.',
    url: 'https://example.com/ai/13',
    urlToImage: 'https://readdy.ai/api/search-image?query=Law%20library%20with%20digital%20holographic%20scales%20of%20justice%20and%20AI%20circuit%20patterns%2C%20academic%20legal%20setting%2C%20professional%20documentary%20photography%2C%20warm%20tones&width=800&height=450&seq=trends-ai-13&orientation=landscape',
    publishedAt: '2026-07-10T10:00:00Z',
    content: 'A medida que los sistemas de IA se vuelven más autónomos, surge una pregunta fundamental para el derecho moderno.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Pedro Alvarez',
    title: 'Apple integra IA generativa en todas sus aplicaciones de productividad',
    description: 'Pages, Numbers y Keynote reciben funciones de generación de texto, análisis de datos y diseño automático impulsadas por modelos en el dispositivo.',
    url: 'https://example.com/ai/14',
    urlToImage: 'https://readdy.ai/api/search-image?query=Apple%20productivity%20apps%20interface%20with%20AI%20features%20on%20MacBook%20Pro%2C%20modern%20office%20desk%20setup%2C%20clean%20Apple%20aesthetic%2C%20natural%20light%20product%20photography&width=800&height=450&seq=trends-ai-14&orientation=landscape',
    publishedAt: '2026-07-09T15:00:00Z',
    content: 'Apple ha anunciado la integración más ambiciosa de inteligencia artificial en su suite de productividad.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Sofia Herrera',
    title: 'Robots con IA conquistan almacenes: Amazon reporta 70% más eficiencia',
    description: 'La integración de robots autónomos con sistemas de IA en centros de distribución reduce costos operativos y tiempos de entrega.',
    url: 'https://example.com/ai/15',
    urlToImage: 'https://readdy.ai/api/search-image?query=Automated%20warehouse%20with%20AI-powered%20robots%20sorting%20packages%20on%20conveyor%20belts%2C%20modern%20logistics%20facility%2C%20industrial%20photography%2C%20blue%20and%20white%20lighting&width=800&height=450&seq=trends-ai-15&orientation=landscape',
    publishedAt: '2026-07-09T11:00:00Z',
    content: 'Amazon ha revelado cifras impresionantes sobre el impacto de la inteligencia artificial en su red logística.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'James Mitchell',
    title: 'Inteligencia artificial predice desastres naturales con 72 horas de anticipación',
    description: 'Un sistema desarrollado por la NASA y Google utiliza machine learning para analizar datos satelitales y predecir huracanes, terremotos e inundaciones.',
    url: 'https://example.com/ai/16',
    urlToImage: 'https://readdy.ai/api/search-image?query=Satellite%20imagery%20analysis%20control%20room%20with%20multiple%20screens%20showing%20weather%20patterns%20and%20AI%20predictions%2C%20NASA-style%20mission%20control%2C%20sci-fi%20documentary%20photography&width=800&height=450&seq=trends-ai-16&orientation=landscape',
    publishedAt: '2026-07-09T08:00:00Z',
    content: 'La colaboración entre la NASA y Google ha producido un sistema de predicción que podría salvar miles de vidas.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: null,
    title: 'Bancos centrales exploran monedas digitales impulsadas por IA para 2030',
    description: 'Varios países anuncian proyectos piloto de CBDC con sistemas inteligentes de detección de fraude y optimización de política monetaria en tiempo real.',
    url: 'https://example.com/ai/17',
    urlToImage: 'https://readdy.ai/api/search-image?query=Central%20bank%20digital%20currency%20concept%20with%20glowing%20digital%20coins%20and%20blockchain%20network%20visualization%2C%20financial%20technology%20aesthetic%2C%20professional%20fintech%20photography&width=800&height=450&seq=trends-ai-17&orientation=landscape',
    publishedAt: '2026-07-08T16:00:00Z',
    content: 'El futuro del dinero podría estar más cerca de lo que pensamos con la integración de inteligencia artificial en monedas digitales.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Elena Vargas',
    title: 'China invierte $50 mil millones en investigación de inteligencia artificial general',
    description: 'El gobierno chino anuncia el mayor programa de inversión en IA de la historia, con el objetivo de liderar el desarrollo de AGI para 2035.',
    url: 'https://example.com/ai/18',
    urlToImage: 'https://readdy.ai/api/search-image?query=Futuristic%20Chinese%20technology%20research%20center%20with%20AI%20innovation%20displays%20and%20modern%20architecture%2C%20government%20technology%20showcase%2C%20clean%20corporate%20photography&width=800&height=450&seq=trends-ai-18&orientation=landscape',
    publishedAt: '2026-07-08T12:00:00Z',
    content: 'China ha anunciado una inversión sin precedentes en el campo de la inteligencia artificial general.',
  },
  {
    source: { id: 'ars-technica', name: 'Ars Technica' },
    author: 'Diego Ramirez',
    title: 'Investigadores crean IA que escribe código más eficiente que programadores senior',
    description: 'El sistema, entrenado con millones de repositorios, optimiza algoritmos reduciendo el consumo energético de centros de datos.',
    url: 'https://example.com/ai/19',
    urlToImage: 'https://readdy.ai/api/search-image?query=Software%20code%20optimization%20visualization%20with%20AI-generated%20algorithm%20patterns%20on%20multiple%20screens%2C%20developer%20workspace%2C%20dark%20mode%20coding%20aesthetic&width=800&height=450&seq=trends-ai-19&orientation=landscape',
    publishedAt: '2026-07-08T09:30:00Z',
    content: 'Un equipo de investigadores ha desarrollado un sistema de IA capaz de escribir código más eficiente que programadores experimentados.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Laura Castillo',
    title: 'Música generada por IA alcanza el número uno en plataformas de streaming',
    description: 'Un álbum creado completamente con inteligencia artificial lidera las listas globales, desatando un intenso debate sobre creatividad y derechos de autor.',
    url: 'https://example.com/ai/20',
    urlToImage: 'https://readdy.ai/api/search-image?query=Music%20streaming%20interface%20with%20AI-generated%20album%20artwork%2C%20modern%20recording%20studio%20with%20digital%20audio%20workstation%2C%20creative%20tech%20photography%2C%20neon%20accent%20lighting&width=800&height=450&seq=trends-ai-20&orientation=landscape',
    publishedAt: '2026-07-07T18:00:00Z',
    content: 'Por primera vez en la historia, un álbum generado completamente por inteligencia artificial ha alcanzado el puesto número uno.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Michael Torres',
    title: 'Microsoft presenta Copilot para empresas: IA que gestiona reuniones y proyectos',
    description: 'La nueva suite empresarial utiliza IA para automatizar actas, asignar tareas y predecir riesgos en proyectos complejos.',
    url: 'https://example.com/ai/21',
    urlToImage: 'https://readdy.ai/api/search-image?query=Microsoft%20Teams%20interface%20with%20Copilot%20AI%20assistant%20features%20on%20modern%20office%20display%2C%20corporate%20meeting%20room%20setting%2C%20business%20technology%20photography&width=800&height=450&seq=trends-ai-21&orientation=landscape',
    publishedAt: '2026-07-07T14:00:00Z',
    content: 'Microsoft ha presentado la evolución más significativa de su asistente de inteligencia artificial para el entorno empresarial.',
  },
  {
    source: { id: 'techcrunch', name: 'TechCrunch' },
    author: 'Maria Gonzalez',
    title: 'Vehículos autónomos con IA alcanzan nivel 5 en pruebas controladas',
    description: 'Waymo y Tesla reportan conducción completamente autónoma sin intervención humana en circuitos cerrados, acercándose al despliegue comercial.',
    url: 'https://example.com/ai/22',
    urlToImage: 'https://readdy.ai/api/search-image?query=Autonomous%20vehicle%20with%20LIDAR%20sensors%20and%20AI%20systems%20on%20test%20track%2C%20futuristic%20automotive%20technology%2C%20clean%20studio%20photography%2C%20dynamic%20motion%20blur&width=800&height=450&seq=trends-ai-22&orientation=landscape',
    publishedAt: '2026-07-07T10:00:00Z',
    content: 'La carrera por el vehículo completamente autónomo ha alcanzado un nuevo hito con los últimos resultados de pruebas.',
  },
  {
    source: { id: 'cnn', name: 'CNN' },
    author: 'Carlos Mendez',
    title: 'Inteligencia artificial revela secretos de antiguos manuscritos ilegibles',
    description: 'Un sistema de IA descifra pergaminos carbonizados de Herculano, revelando textos filosóficos perdidos durante 2000 años.',
    url: 'https://example.com/ai/23',
    urlToImage: 'https://readdy.ai/api/search-image?query=Ancient%20charred%20scroll%20fragments%20being%20digitally%20reconstructed%20with%20AI%20on%20laboratory%20screen%2C%20archaeological%20research%20setting%2C%20historical%20discovery%20photography%2C%20warm%20sepia%20tones&width=800&height=450&seq=trends-ai-23&orientation=landscape',
    publishedAt: '2026-07-06T16:00:00Z',
    content: 'La inteligencia artificial está ayudando a los arqueólogos a desvelar secretos que han permanecido ocultos durante milenios.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'Ana Torres',
    title: 'ONU crea agencia internacional para supervisar el desarrollo de IA avanzada',
    description: 'La nueva entidad tendrá autoridad para auditar sistemas de IA de alto riesgo y emitir recomendaciones vinculantes a los países miembros.',
    url: 'https://example.com/ai/24',
    urlToImage: 'https://readdy.ai/api/search-image?query=United%20Nations%20general%20assembly%20hall%20with%20digital%20AI%20governance%20displays%2C%20diplomatic%20international%20setting%2C%20formal%20institutional%20photography%2C%20world%20flags%20background&width=800&height=450&seq=trends-ai-24&orientation=landscape',
    publishedAt: '2026-07-06T12:00:00Z',
    content: 'Las Naciones Unidas han dado un paso histórico hacia la gobernanza global de la inteligencia artificial.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: null,
    title: 'Startups de IA atraen inversión récord de $80 mil millones en primer semestre',
    description: 'El capital de riesgo destinado a inteligencia artificial duplica las cifras del año anterior, consolidando al sector como líder indiscutible en inversión tecnológica.',
    url: 'https://example.com/ai/25',
    urlToImage: 'https://readdy.ai/api/search-image?query=Venture%20capital%20investment%20meeting%20with%20AI%20startup%20pitch%20deck%20and%20financial%20charts%2C%20modern%20boardroom%2C%20business%20finance%20photography%2C%20glass%20wall%20and%20city%20view&width=800&height=450&seq=trends-ai-25&orientation=landscape',
    publishedAt: '2026-07-06T09:00:00Z',
    content: 'El sector de inteligencia artificial continúa batiendo récords de inversión a nivel global.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Sofia Herrera',
    title: 'IA cuántica: la próxima frontera que combina dos tecnologías revolucionarias',
    description: 'Investigadores del MIT logran ejecutar modelos de machine learning en procesadores cuánticos, abriendo posibilidades antes inimaginables.',
    url: 'https://example.com/ai/26',
    urlToImage: 'https://readdy.ai/api/search-image?query=Quantum%20computer%20laboratory%20with%20superconducting%20processor%20and%20AI%20visualization%20screens%2C%20cutting-edge%20research%20facility%2C%20futuristic%20scientific%20photography%2C%20blue%20cryogenic%20lighting&width=800&height=450&seq=trends-ai-26&orientation=landscape',
    publishedAt: '2026-07-05T15:00:00Z',
    content: 'La intersección entre computación cuántica e inteligencia artificial promete revolucionar ambos campos.',
  },
  {
    source: { id: 'wired', name: 'Wired' },
    author: 'Michael Torres',
    title: 'Redes sociales implementan verificación de contenido con IA multimodal',
    description: 'Las principales plataformas adoptan sistemas que analizan simultáneamente texto, imágenes y video para detectar desinformación de manera más efectiva.',
    url: 'https://example.com/ai/27',
    urlToImage: 'https://readdy.ai/api/search-image?query=Social%20media%20content%20moderation%20dashboard%20with%20AI%20flagging%20system%20on%20large%20screen%2C%20modern%20tech%20office%2C%20digital%20safety%20photography%2C%20purple%20and%20blue%20UI&width=800&height=450&seq=trends-ai-27&orientation=landscape',
    publishedAt: '2026-07-05T10:00:00Z',
    content: 'Las redes sociales están desplegando sistemas de inteligencia artificial cada vez más sofisticados para combatir la desinformación.',
  },
  {
    source: { id: 'the-verge', name: 'The Verge' },
    author: 'Pedro Alvarez',
    title: 'Google DeepMind crea IA que aprende física intuitiva como un niño',
    description: 'El sistema observa videos y desarrolla comprensión de conceptos como gravedad y colisiones sin entrenamiento explícito en leyes físicas.',
    url: 'https://example.com/ai/28',
    urlToImage: 'https://readdy.ai/api/search-image?query=AI%20system%20watching%20videos%20of%20physical%20objects%20and%20learning%20intuitive%20physics%2C%20research%20lab%20with%20neural%20network%20visualization%2C%20scientific%20computing%20photography&width=800&height=450&seq=trends-ai-28&orientation=landscape',
    publishedAt: '2026-07-04T16:00:00Z',
    content: 'DeepMind ha logrado un avance fascinante en la intersección entre inteligencia artificial y ciencias cognitivas.',
  },
  {
    source: { id: 'bbc-news', name: 'BBC News' },
    author: 'Laura Castillo',
    title: 'Agricultura inteligente: drones con IA aumentan rendimiento de cultivos en 40%',
    description: 'Agricultores en Kenia e India reportan resultados extraordinarios usando sistemas de IA para monitoreo, riego y control de plagas.',
    url: 'https://example.com/ai/29',
    urlToImage: 'https://readdy.ai/api/search-image?query=AI-powered%20agricultural%20drone%20flying%20over%20green%20crop%20fields%20with%20data%20overlay%2C%20sustainable%20farming%20technology%2C%20warm%20natural%20daylight%2C%20rural%20landscape%20photography&width=800&height=450&seq=trends-ai-29&orientation=landscape',
    publishedAt: '2026-07-04T09:00:00Z',
    content: 'La inteligencia artificial está transformando la agricultura en algunas de las regiones más vulnerables del planeta.',
  },
  {
    source: { id: 'reuters', name: 'Reuters' },
    author: 'James Mitchell',
    title: 'Sindicatos globales exigen tratado internacional sobre IA y empleo',
    description: 'Organizaciones laborales de 50 países se unen para demandar protecciones contra la automatización masiva y programas garantizados de transición laboral.',
    url: 'https://example.com/ai/30',
    urlToImage: 'https://readdy.ai/api/search-image?query=International%20labor%20union%20conference%20with%20diverse%20workers%20and%20digital%20rights%20displays%2C%20formal%20convention%20center%20setting%2C%20documentary%20photojournalism%2C%20natural%20lighting&width=800&height=450&seq=trends-ai-30&orientation=landscape',
    publishedAt: '2026-07-03T18:00:00Z',
    content: 'El movimiento sindical global ha lanzado una campaña coordinada para enfrentar los desafíos laborales de la inteligencia artificial.',
  },
];